### ISSUE TITLE
is it possible to do translation?

### ISSUE THREAD

**Issue by EloneSampaio** [papyrussolution/OpenPapyrus#7]
how to translate this system to portuguese??

**Comment by papyrussolution** [comment]
There is an experimental translation to the english, german and dutch languages. You can launch the application with the command line key /uilang:en (/uilang:nl, /uilang:nl). E.g. ppw.exe /uilang:en
I must make an emphasis on the word "experimental": the real translation has been made with the help of the autotranslation service.
As soon as you asked we will add the portuguese language, but the quality will be still very poor until we finished infrastructure works on the localization problem in common.

**Comment by EloneSampaio** [comment]
Got it, I'll test thanks.
